import { useCallback, useEffect, useRef, useState } from 'react';
import {
  dashboardSnapshotError,
  fetchCsatReport,
  fetchDashboardData,
  fetchSfReportIndex,
  pickCsatExport,
  requiresDashboardSnapshot,
  type CsatReport,
} from '@/lib/sf-reports';

export type CsatReportState =
  | { status: 'loading' }
  | { status: 'error'; message: string }
  | { status: 'ready'; report: CsatReport; refreshError?: string };

export interface CsatReportController {
  state: CsatReportState;
  refreshing: boolean;
  reload: () => void;
}

/**
 * Loads the CSAT report. Prefers the pre-parsed dashboard-data.json (fast,
 * generated by `sync:reports`); falls back to runtime parsing of the newest
 * CSAT .xlsx in sf_reports/ if the JSON is absent or lacks a csat section.
 */
export function useCsatReport(): CsatReportController {
  const [state, setState] = useState<CsatReportState>({ status: 'loading' });
  const [refreshing, setRefreshing] = useState(false);
  const [nonce, setNonce] = useState(0);
  const hasLoadedOnce = useRef(false);

  const reload = useCallback(() => {
    if (hasLoadedOnce.current) setRefreshing(true);
    setNonce((n) => n + 1);
  }, []);

  useEffect(() => {
    let cancelled = false;
    const controller = new AbortController();

    (async () => {
      try {
        // Fast path: pre-computed JSON.
        const pre = await fetchDashboardData(controller.signal, nonce > 0);
        if ((nonce === 0 || requiresDashboardSnapshot()) && pre?.csat) {
          if (cancelled) return;
          setState({ status: 'ready', report: pre.csat });
          hasLoadedOnce.current = true;
          return;
        }
        if (requiresDashboardSnapshot()) throw new Error(dashboardSnapshotError());
        // Fallback: parse the newest export at runtime.
        const files = await fetchSfReportIndex(controller.signal);
        const file = pickCsatExport(files);
        if (!file) throw new Error('No CSAT .xlsx export found in sf_reports/');
        const report = await fetchCsatReport(file, controller.signal);
        if (cancelled) return;
        setState({ status: 'ready', report });
        hasLoadedOnce.current = true;
      } catch (e) {
        if (cancelled || (e instanceof DOMException && e.name === 'AbortError')) return;
        const message = e instanceof Error ? e.message : String(e);
        setState((current) => current.status === 'ready'
          ? { ...current, refreshError: message }
          : { status: 'error', message });
        hasLoadedOnce.current = true;
      } finally {
        if (!cancelled) setRefreshing(false);
      }
    })();

    return () => {
      cancelled = true;
      controller.abort();
    };
  }, [nonce]);

  return { state, refreshing, reload };
}
