/**
 * Roster index — maps month keys to their roster arrays.
 * Auto-generated by scripts/sync-roster.mjs.
 */

import type { RosterAgent } from './roster';
import { ROSTER_202610 } from './roster-2026-10';
import { ROSTER_202611 } from './roster-2026-11';

const ROSTERS: Record<string, RosterAgent[]> = {
  '2026-10': ROSTER_202610,
  '2026-11': ROSTER_202611,
};

/** Returns the roster for the given month key (YYYY-MM), or undefined. */
export function getRoster(monthKey: string): RosterAgent[] | undefined {
  return ROSTERS[monthKey];
}

/** All available roster month keys, sorted. */
export const ROSTER_MONTHS = Object.keys(ROSTERS).sort();
